# Generated by Django 3.2.5 on 2022-01-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_review_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='aired_At',
            new_name='aired_at',
        ),
    ]
